"""Backward-compatible re-export shim for legacy utility imports."""

from hashcrush.executor.hashcat_command import (
    build_hashcat_argv,
    build_hashcat_command,
    format_hashcat_speed,
)
from hashcrush.hashfiles.validation import (
    _get_hashfile_validation_limit,
    _iter_hashfile_lines,
    import_hash_only,
    import_hashfilehashes,
    normalize_hashfile_file_type,
    normalize_hash_type,
    validate_hash_only_hashfile,
    validate_kerberos_hashfile,
    validate_netntlm_hashfile,
    validate_pwdump_hashfile,
    validate_shadow_hashfile,
    validate_user_hash_hashfile,
)
from hashcrush.jobs.status import update_job_task_status
from hashcrush.utils.file_ops import get_filehash, get_linecount, get_md5_hash, save_file
from hashcrush.utils.secret_storage import (
    decode_ciphertext_from_storage,
    decode_plaintext_from_storage,
    decode_username_from_storage,
    encode_ciphertext_for_storage,
    encode_plaintext_for_storage,
    encode_username_for_storage,
    get_ciphertext_search_digest,
    get_plaintext_search_digest,
    get_username_search_digest,
    is_plaintext_hex_encoded,
    migrate_plaintext_storage_rows,
    migrate_sensitive_storage_rows,
)
from hashcrush.utils.storage_paths import (
    get_runtime_root_path,
    get_runtime_subdir,
    get_storage_root_path,
    get_storage_subdir,
    resolve_stored_path as _resolve_storage_path,
    utc_now_naive as _utc_now_naive,
)
from hashcrush.wordlists.dynamic import update_all_dynamic_wordlists, update_dynamic_wordlist

__all__ = [
    "_get_hashfile_validation_limit",
    "_iter_hashfile_lines",
    "_resolve_storage_path",
    "_utc_now_naive",
    "build_hashcat_argv",
    "build_hashcat_command",
    "decode_ciphertext_from_storage",
    "decode_plaintext_from_storage",
    "decode_username_from_storage",
    "encode_ciphertext_for_storage",
    "encode_plaintext_for_storage",
    "encode_username_for_storage",
    "format_hashcat_speed",
    "get_ciphertext_search_digest",
    "get_filehash",
    "get_linecount",
    "get_md5_hash",
    "get_plaintext_search_digest",
    "get_runtime_root_path",
    "get_runtime_subdir",
    "get_storage_root_path",
    "get_storage_subdir",
    "get_username_search_digest",
    "import_hash_only",
    "import_hashfilehashes",
    "normalize_hashfile_file_type",
    "is_plaintext_hex_encoded",
    "migrate_plaintext_storage_rows",
    "migrate_sensitive_storage_rows",
    "normalize_hash_type",
    "save_file",
    "update_all_dynamic_wordlists",
    "update_dynamic_wordlist",
    "update_job_task_status",
    "validate_hash_only_hashfile",
    "validate_kerberos_hashfile",
    "validate_netntlm_hashfile",
    "validate_pwdump_hashfile",
    "validate_shadow_hashfile",
    "validate_user_hash_hashfile",
]
